apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
  labels:
    app: training
spec:
  template:
    metadata:
      labels:
        app: training
    spec:
      restartPolicy: Never
      containers:
      - name: trainer
        image: python:3.12-slim
        command:
        - /bin/bash
        - -c
        - |
          pip install mlflow scikit-learn pandas boto3 && \
          cd /code && \
          python ml/ml-log-loki/scripts/train_log_clustering.py --experiment-name "loki-prod" --register-model --model-name log-clustering-kmeans --promote-to-production
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio-service:9000"
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin"
        volumeMounts:
        - name: training-code
          mountPath: /code
      volumes:
      - name: training-code
        hostPath:
          path: /home/ubuntu/monitoring-ia
          type: Directory
  backoffLimit: 2
